#!/bin/bash

# Justino justino@icm.csic.es
# WW3 tools
# Creates the obstruction file from the WW3 grid generated by coarse.py and the file .mat converted by coord2latlon.py
#

# Where is create_obstr.m and the rest of the matlabs provided by GRIDGEN
MATLAB_progs="/data/lustre/WW3/TUTORIAL_GRIDGEN/bin"

# Matlab executable
MATLAB=matlab

# Input files
filex="CATSEA_x_4.inp"
filey="CATSEA_y_4.inp"
filem="CATSEA_4.mask_nobound"
filemat="coastal_bound_CATSEA.mat"

# Output file
fileo="CATSEA_4.obst"

#######################################################
#
if [ ! -f ${MATLAB_progs}/create_obstr.m ]; then
	echo "Please, indicate where create_obstr.m is located by correcting the MATLAB_progs variable in the code"
	exit
fi
if [ ! -f ${filex} ]; then
	echo "Please, check the name of input files"
	exit
fi

cat ${filex} | sed 's|  |,|g' > /tmp/sx
cat ${filey} | sed 's|  |,|g' > /tmp/sy
cat ${filem} | sed 's|  |,|g' > /tmp/mask

cat <<EOF > script$$.m
addpath('$MATLAB_progs');
lon=csvread('/tmp/sx');
lat=csvread('/tmp/sy');
mask=csvread('/tmp/mask');
load('$filemat');
[Sx,Sy]=create_obstr(lon,lat,bound,mask,1,1);
csvwrite('/tmp/sx.dat',Sx);
csvwrite('/tmp/sy.dat',Sy);
EOF

${MATLAB} -nodisplay -nodesktop -nosplash -nojvm -r "try, script$$;  catch, disp('failed execution'), end, quit"

rm /tmp/sx /tmp/sy /tmp/mask script$$.m 
if [ ! -f /tmp/sx.dat ] || [ ! -f /tmp/sy.dat ]; then
	echo "Error in MATLAB"
	exit

fi

sed -i 's|,|  |g' /tmp/sx.dat
sed -i -e 's|^| |g' /tmp/sx.dat
sed -i 's|,|  |g' /tmp/sy.dat
sed -i -e 's|^| |g' /tmp/sy.dat
cat /tmp/sx.dat > ${fileo}
echo "" >> ${fileo}
cat /tmp/sy.dat >> ${fileo}

echo "File ${fileo} has been created"

rm /tmp/sx.dat /tmp/sy.dat
