#!/usr/bin/env python3
#
# Justino justino@icm.csic.es
# WW3 tools 
# Generates a WW3 restart file for OASIS with calm conditions
#
# Input parameters:
#
#	For 'RECT' grid (1D lat,lon)
#	1.- The grid file ".meta"
#	2.- The output netcdf filename (typically ww3_restart.nc)
#
#	For 'CURV' grid (2D lat,lon)
#	1.- The grid file ".inp" containing x (longitude) values
#	2.- The grid file ".inp" containing y (latitude) values
#	3.- The output netcdf filename (typically ww3_restart.nc)

import sys,re
import numpy as np
from netCDF4 import Dataset

# Reads meta file ang generates the values for lat/lon
def readMeta(filename):
	
	text_file = open(filename,'r')
	file_lines = text_file.readlines()
	
	keys=['RECT%NX','RECT%NY','RECT%SX ','RECT%SY','RECT%X0','RECT%Y0']

	value = {}
	for line in file_lines:
		# Flag is True if the line starts (special character for start: \A) with 'Id of the track'
		curr=None		
		for k in keys:			
			flag = re.search(k,line)
			if flag:
				curr=k
				break
		if curr is not None:		
			line=line.replace(" ","")
			line=line.replace("\t","")
			line=line.replace("\n","")
			value[curr] = float(re.search(r'\=(.*)',line).group(1))
	
	Nx,Ny,Sx,Sy,X0,Y0=[value[k] for k in keys]
	Nx=int(Nx)
	Ny=int(Ny)
	lon=np.zeros(Nx)
	lat=np.zeros(Ny)
	for i in range(Nx):
		lon[i]=X0+i*Sx
	for i in range(Ny):
		lat[i]=Y0+i*Sy
		
	return lon,lat		
	
def main():	 
	RECT=False # Not rectilinear by default
	if len(sys.argv) < 3 or len(sys.argv) > 4:		
			print("Usage for rect grids:"+sys.argv[0]+" .meta output.nc")
			print("Usage for curv grids:"+sys.argv[0]+" _x.inp _y.inp output.nc")
			sys.exit(-1)
	if len(sys.argv) == 3:
		RECT=True
		
	if RECT==True:		
		# ------------------------------------------------------------
		# Grid data in meta file generated by gridgem tools
		# ------------------------------------------------------------
		metafile = sys.argv[1]
		ncfile = sys.argv[2]	
		lon,lat = readMeta(metafile) # 1D vectors
		Nx=len(lon)
		Ny=len(lat)
	else: 		
		# ------------------------------------------------------------
		# Input ASCII files in Nx x Ny format
		# ------------------------------------------------------------
		lon_file = sys.argv[1]
		lat_file = sys.argv[2]	
		ncfile = sys.argv[3]		
		# Load ASCII grids (N rows × M columns) 2D arrays
		lon = np.loadtxt(lon_file)
		lat = np.loadtxt(lat_file)
	
		# Check dimensions
		Ny, Nx = lat.shape
		assert lon.shape == (Ny, Nx)
	
	# ------------------------------------------------------------
	# Create output NetCDF
	# ------------------------------------------------------------
	ds = Dataset(ncfile, "w", format="NETCDF4")
	
	# Create dimensions
	ds.createDimension("latitude", Ny)
	ds.createDimension("longitude", Nx)
	
	# Create coordinate variables (CF conventions)
	if RECT==True:
		latitudes  = ds.createVariable("latitude",  "f4", ("latitude"))
		longitudes = ds.createVariable("longitude", "f4", ("longitude"))
	else:
		latitudes  = ds.createVariable("latitude",  "f4", ("latitude", "longitude"))
		longitudes = ds.createVariable("longitude", "f4", ("latitude", "longitude"))
	WW3_T0M1 = ds.createVariable("WW3_T0M1",  "f8", ("latitude", "longitude"))
	WW3__OHS = ds.createVariable("WW3__OHS",  "f8", ("latitude", "longitude"))
	WW3__DIR = ds.createVariable("WW3__DIR",  "f8", ("latitude", "longitude"))
	# metadata
	
	latitudes.axis = "Y" 
	latitudes.long_name = "latitude" 
	latitudes.standard_name = "latitude" 
	latitudes.units = "degree_north" 
	latitudes.valid_max = 90.0 
	latitudes.valid_min = -90.0

	longitudes.units = "degree_east" 
	longitudes.long_name = "longitude" 
	longitudes.standard_name = "longitude" 
	longitudes.valid_min = -180.0 
	longitudes.valid_max = 360.0
	longitudes.axis = "X" 
	
	
	WW3_T0M1.long_name = "status map"
	WW3_T0M1.standard_name = "status map"
	WW3_T0M1.units = "1"
	WW3_T0M1.valid_max = 32.
	WW3_T0M1.valid_min = -32.

	WW3__OHS.long_name = "status map"
	WW3__OHS.standard_name = "status map"
	WW3__OHS.units = "1"
	WW3__OHS.valid_max = 32.
	WW3__OHS.valid_min = -32.

	WW3__DIR.long_name = "status map"
	WW3__DIR.standard_name = "status map"
	WW3__DIR.units = "1"
	WW3__DIR.valid_max = 32.
	WW3__DIR.valid_min = -32.
	
	

	# Write data
	if RECT==True:
		latitudes[:] = lat
		longitudes[:] = lon
	else:
		latitudes[:, :] = lat
		longitudes[:, :] = lon
	WW3_T0M1[:,:]=np.zeros((Ny,Nx))
	WW3__OHS[:,:]=np.zeros((Ny,Nx))
	WW3__DIR[:,:]=np.zeros((Ny,Nx))
	# Close file
	ds.close()
	
	print("NetCDF file created:", ncfile)
if __name__ == "__main__":
	main()